title:  "Ecosherwood"
description:

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'About Us', file: 'about.html'}
- {name: 'Our Project', file: "our_project.html"}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'envelope', link: 'mailto:ecosherwoodshs@gmail.com}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
